targets:
   $default:
      builders:
         freezed:freezed:
            generate_for:
               include:
                  - lib/src/features/**/models/**.dart
         injectable_generator|injectable_config_builder:
            enabled: true
            generate_for:
               include:
                  - lib/src/core/di/**.dart
                  - lib/src/core/log/**.dart
                  - lib/src/core/network/**.dart
                  - lib/src/core/storage/**.dart
                  - lib/src/features/**/data/datasources/**.dart
                  - lib/src/features/**/data/repositories/**.dart
                  - lib/src/features/**/domain/usecases/**.dart
                  - lib/src/list/**.dart
                  - lib/src/shared/data/**/**.dart
                  - lib/src/view/**.dart
         envied_generator:
            enabled: true
            generate_for:
               include:
                  - lib/src/config/**.dart
