name: stadata_workspace
repository: https://github.com/ryanaidilp/stadata_flutter_sdk
packages:
  - app/*
  - packages/*

command:
  version:
    changelogs:
      - path: CHANGELOG.md
        packageFilters:
          scope: none
  bootstrap:
    hooks:
      post: melos run build
  clean:
    hooks:
      post: |
        melos exec --flutter --concurrency=3 -- "flutter clean"
        melos run build:clean

scripts:
  get:select:
    run: melos exec -- "flutter pub get"
    description: "Run `flutter pub get` in selected package."
    packageFilters:
      dependsOn: flutter

  get:
    run: melos run get:select --no-select
    description: "Run `flutter pub get` in all packages that depends on Flutter."

  build:
    run: melos run build:select --no-select
    description: "Run build runer in all packages"

  build:select:
    run: melos exec -- "dart run build_runner build -d"
    description: "Run build_runner in selected package that depends on build_runner."
    packageFilters:
      dependsOn:
        - "build_runner"

  build:clean:
    run: melos run build:clean:select --no-select
    description: "Run build runner clean in all packages that depend on it."

  build:clean:select:
    run: melos exec -- "dart run build_runner clean"
    description: "Run build runner clean in selected package that depends on build_runner."
    packageFilters:
      dependsOn:
        - "build_runner"

  fix:
    run: melos run fix:select --no-select
    description: "Fix syntax violation in all packages."

  fix:select:
    run: melos exec -- "dart fix --apply"
    description: "Fix syntax violation in selected package."

  upgrade:select:
    run: melos exec -- "flutter pub upgrade"
    description: "Run `flutter pub upgrade` in selected package."
    packageFilters:
      dependsOn: "flutter"
  upgrade:
    run: melos run upgrade:select --no-select
    description: "Run `flutter pub upgrade` in all packages."
