targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        enabled: true
        generate_for:
          include:
            - lib/features/**/presentation/pages/**.dart
      auto_route_generator:auto_router_generator:
        enabled: true
        generate_for:
          include:
            - lib/core/navigation/**.dart
      envied_generator:envied:
        enabled: true
        generate_for:
          include:
            - lib/config/**.dart
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - lib/**/*.g.dart
            - lib/**/*.gr.dart
            - lib/**/*.config.dart
      injectable_generator:injectable_config_builder:
        enabled: true
        generate_for:
          include:
            - lib/**/*.dart
      slang_build_runner:
        options:
          base_locale: en
          input_directory: lib/translations
          input_file_pattern: .i18n.json
          output_directory: lib/core/generated
          string_interpolation: dart
          namespaces: false
          translate_var: t
          enum_name: AppLocale
          class_name: Translations
          translation_class_visibility: private
          key_case: camel
          key_map_case: camel
          param_case: camel
          string_interpolation_dart:
            escape_dollar: false
