targets:
   $default:
      builders:
         json_serializable:
            options:
               field_rename: snake
         freezed:freezed:
            generate_for:
               include:
                  - lib/src/features/**/models/**.dart
