name: stadata_flutter_sdk
description: |
  Streamline BPS Statistics API integration in Flutter. Easily fetch, analyze, and visualize data.
homepage: https://ryanaidilp.github.io/stadata-flutter-sdk-docs/
repository: https://github.com/ryanaidilp/stadata_flutter_sdk
version: 0.7.1
# publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  dio_smart_retry: ">=5.0.0 <7.0.0"
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logger: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://saweria.co/ryanaidilp
