name: stadata_flutter_sdk
description: |
  Streamline BPS Statistics API integration in Flutter. Easily fetch, analyze, and visualize data.
homepage: https://ryanaidilp.github.io/stadata_flutter_sdk/
repository: https://github.com/ryanaidilp/stadata_flutter_sdk
version: 0.8.1
# publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  html_unescape: ^2.0.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://saweria.co/ryanaidilp

topics:
  - data
  - api