name: stadata_flutter_sdk
description: |
  Streamline BPS Statistics API integration in Flutter. Easily fetch, analyze, and visualize data.
homepage: https://ryanaidilp.github.io/stadata_flutter_sdk/
repository: https://github.com/ryanaidilp/stadata_flutter_sdk
version: 0.8.0
# publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  dartz: ^0.10.1
  dio: ^5.5.0+1
  dio_cache_interceptor: ^3.5.0
  dio_smart_retry: ">=5.0.0 <7.0.0"
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://saweria.co/ryanaidilp
