name: stadata_flutter_sdk
description: |
  Streamline BPS Statistics API integration in Flutter. Easily fetch, analyze, and visualize data.
homepage: https://ryanaidilp.github.io/stadata_flutter_sdk/
repository: https://github.com/ryanaidilp/stadata_flutter_sdk
version: 0.8.2
# publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
resolution: workspace

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  html_unescape: ^2.0.0
  logger: ^2.6.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://saweria.co/ryanaidilp

topics:
  - data
  - api
