name: Notify Discord on Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
      release_url:
        description: "Release URL"
        required: true
      release_name:
        description: "Release name"
        required: true
      tag_name:
        description: "Tag name"
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests

      - name: Notify Discord
        env:
          DISCORD_RELEASE_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
          DISCORD_MAP: ${{ secrets.DISCORD_MAP }}
          RELEASE_VERSION: ${{ github.event.release.tag_name || inputs.tag_name }}
          RELEASE_NAME: ${{ github.event.release.name || inputs.release_name }}
          RELEASE_URL: ${{ github.event.release.html_url || inputs.release_url }}
          RELEASE_BODY: ${{ github.event.release.body }}
          REPO_NAME: ${{ github.repository }}
          PUBLISHER: ${{ github.event.release.author.login || github.actor }}
        run: python .github/scripts/notify_discord_release.py
